# Numpy

- Import Numpy
- Mathmatical Operations
- Array Creation
- Adding Dimension
- np.zeros
- np.eye
- np.empty
- np.full
- np.arange   / array range
- np.linspace  (differnce between arange & linspace)
- random & randomn, randint
- Types of Array
- NDarray, item, itemsize
- Slicing

In [193]:
import numpy as np
np.__version__

'1.23.3'

# Math Computational

In [194]:
summ = 0
for num in range(1, 9999999):
    summ += num**2*3

summ

999999550000064999997

In [195]:
np.arange(1,9999999)

array([      1,       2,       3, ..., 9999996, 9999997, 9999998])

## Comparing Computational efficiency between general & numpy

In [196]:
# General Python, takes more time
summ1 = 0
for num in range (1,99999999):
    summ1 += num

summ1

4999999850000001

In [197]:
# Numpy sum operation     takes less time, in case of huge data we will see the different more clearly
np.sum(np.arange(1,99999999, dtype=np.int64))

4999999850000001

In [198]:
np.arange(99999999, dtype=np.int64).sum()   # alternative syntax of doing sum aggregation over numpy

4999999850000001

### Numpy is more efficinet
- Previous one needs more time than numpy
- for this operation, numpy is not taking for loop, while for same general python using loop

# Array Creation

In [199]:
# np.zeros([shape size] comma dtype with np.bit size)  # Syntax
np.zeros([3,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [200]:
np.zeros([5,5], dtype=np.int64)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [201]:
np.zeros([4, 4], dtype=np.float64)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [202]:
np.zeros([2,2], dtype=np.float16)

array([[0., 0.],
       [0., 0.]], dtype=float16)

In [203]:
np.zeros([4,3], dtype=np.int64)  # rows & columns is 4:3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [204]:
np.zeros([5,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

### Adding Demension

In [205]:
np.zeros([4,3,2], dtype=np.int64)  
# 4 rows, 3 columns and 2 cell/value per row  or for each row, here is adding dimenstion as 2

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=int64)

In [206]:
np.zeros([4,3,3], dtype=np.int64)    # 3 cell/ value per row

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [207]:
np.zeros([4,3,4], dtype=np.int64)    # 4 cell/ value per row

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)

In [208]:
np.zeros([4,3,5], dtype=np.int64)    # 5 cell/ value per row

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [209]:
np.zeros([4,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [210]:
np.zeros([4,5,10], dtype=np.int64)   # 10 dimension

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [211]:
np.zeros([4,8,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0

In [212]:
np.zeros([4,3,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [213]:
np.zeros([4,2,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [214]:
np.ones([4,4])    # by default dtype takes float & mentioning dtype is optional

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [215]:
np.ones([4,4], dtype=np.float64)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [216]:
np.ones([4,4], dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [217]:
np.eye(3,3)     # np.eye means "Identity Matrix", eye operation will not take square bracket [], np.eye takes only "tuple"

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [218]:
np.eye(3,3, k=1)    # by default k = 0

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [219]:
np.eye(6,6)       # default k = 0

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [220]:
np.eye(6,6, k=0)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [221]:
np.eye(6,6, k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [222]:
np.eye(6,6, k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [223]:
np.eye(6,6, k=4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [224]:
np.eye(6,6, k=-4)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [225]:
np.eye(6,6, k=5)

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [226]:
np.eye(3,3, k=-1) 

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [227]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [228]:
np.eye(3,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [229]:
np.eye(3,4,-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [230]:
np.eye(3,4,3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [231]:
np.eye(3,4,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [232]:
np.empty([3,3])

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [233]:
np.empty([3,3,3])

array([[[1.14410197e-311, 8.25089629e-322, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 1.15998412e-028],
        [4.31603868e-080, 1.94919985e-153, 1.35717430e+131]],

       [[4.57669057e-072, 1.81148490e-152, 6.14099335e-071],
        [1.05132387e-153, 6.01391519e-154, 1.05135742e-153],
        [8.15766128e+140, 6.01347002e-154, 8.01768646e-096]],

       [[5.49891556e-095, 8.78959876e+198, 2.18229349e-094],
        [1.43267083e+161, 2.20832505e-094, 9.80058441e+252],
        [1.23971686e+224, 2.59923248e-306, 0.00000000e+000]]])

In [234]:
np.empty([3,3,2])

array([[[1.37962049e-306, 1.24610791e-306],
        [1.11260959e-306, 1.69109959e-306],
        [9.34603679e-307, 1.42419802e-306]],

       [[1.78019082e-306, 4.45061456e-308],
        [1.24612081e-306, 1.37962049e-306],
        [9.34597567e-307, 1.29061821e-306]],

       [[1.78019625e-306, 1.11255866e-306],
        [8.90098127e-307, 9.34609790e-307],
        [3.91792279e-317, 2.44771535e-307]]])

In [235]:
np.empty([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [236]:
np.full([3,3], 8.5)   # it will fill the 3x3 matrix with 8.5

array([[8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5]])

In [237]:
np.full([3,3], 10.5)

array([[10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5]])

### Arange

- np.arange will not take squre backet
- mentioning dtype is optional
- it will take (start: end: step size)
- default takes int
- float & int can be mentioned in dtype
- its like a range function
- it can be reshaped

In [238]:
np.arange(1,100)   

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [239]:
np.arange(1,100, dtype=np.int64) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int64)

In [240]:
np.arange(1,100, dtype=np.float64) 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 65.,
       66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77., 78.,
       79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91.,
       92., 93., 94., 95., 96., 97., 98., 99.])

In [241]:
np.arange(1,100,5)    # step size = 5

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [242]:
np.arange(0,100,5) 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [243]:
np.linspace(1,10, 500)  # in a range 1 to 10 , it will return 500 random values

array([ 1.        ,  1.01803607,  1.03607214,  1.05410822,  1.07214429,
        1.09018036,  1.10821643,  1.12625251,  1.14428858,  1.16232465,
        1.18036072,  1.19839679,  1.21643287,  1.23446894,  1.25250501,
        1.27054108,  1.28857715,  1.30661323,  1.3246493 ,  1.34268537,
        1.36072144,  1.37875752,  1.39679359,  1.41482966,  1.43286573,
        1.4509018 ,  1.46893788,  1.48697395,  1.50501002,  1.52304609,
        1.54108216,  1.55911824,  1.57715431,  1.59519038,  1.61322645,
        1.63126253,  1.6492986 ,  1.66733467,  1.68537074,  1.70340681,
        1.72144289,  1.73947896,  1.75751503,  1.7755511 ,  1.79358717,
        1.81162325,  1.82965932,  1.84769539,  1.86573146,  1.88376754,
        1.90180361,  1.91983968,  1.93787575,  1.95591182,  1.9739479 ,
        1.99198397,  2.01002004,  2.02805611,  2.04609218,  2.06412826,
        2.08216433,  2.1002004 ,  2.11823647,  2.13627255,  2.15430862,
        2.17234469,  2.19038076,  2.20841683,  2.22645291,  2.24

##### arange return value within a range with or without step size, linspace return values in a range with asked number of values to be returned

In [244]:
np.random.randint(2,4)

2

In [245]:
np.random.randint(2,10)

9

In [246]:
np.random.randn(50)   # As I want 50 random value

array([ 1.77630421,  0.39695352,  0.85524111,  0.49470679,  2.30534329,
        1.85778956, -0.88051665, -0.86345696,  0.82219775, -1.06381997,
       -1.83837996, -0.40070681,  1.36212598,  0.03144252, -0.1533264 ,
       -0.84961782,  0.58545555,  1.38398763,  0.49177306,  0.35627133,
       -0.82626635,  0.82058867,  0.95588847,  0.62285106, -1.0851947 ,
        2.68057443, -0.54311531,  1.23095128,  0.09124117,  0.89211524,
        0.13829639,  1.06779953, -0.19578355,  0.42332392,  1.06314035,
       -0.79043849, -1.66444017,  1.09093346, -0.99327429, -0.88771843,
       -1.44171957, -0.27142989, -0.04253723,  1.31420643, -0.21731895,
       -1.18357951, -2.26470393, -0.2374272 , -1.12227708, -0.87210727])

In [247]:
np.random.randn(1,15, 5) 

array([[[ 1.13388515,  1.01058711, -0.71331156, -0.90785645,
          0.37841628],
        [-0.41054067,  0.78227455,  0.43189647,  0.69796182,
         -0.10715658],
        [-0.32953489, -3.34885829, -0.39564759, -0.32276598,
         -1.25813028],
        [-0.07000501,  1.10028008,  0.17893464, -1.08367028,
         -0.03232276],
        [ 0.14121705,  0.14594727,  0.52865128, -0.19762642,
          1.84609954],
        [ 0.76905834,  0.05845193,  1.20505759, -0.86817365,
         -0.21198211],
        [-0.9342976 , -1.06578026, -1.54075949, -0.18750926,
          0.70159695],
        [-2.77660279, -0.24751542, -0.54938195, -0.42044022,
         -0.34332651],
        [-0.81513893, -1.77752614, -0.40511996,  1.39549659,
          0.908286  ],
        [-0.05355661,  0.1661128 ,  0.36140393,  0.55195094,
          1.05594601],
        [ 0.41778725, -1.59272311, -1.91974306, -1.52853717,
         -0.47794275],
        [ 0.3010704 , -1.55143893, -0.06601224,  1.78681445,
          1.408

# Types of Array

- Convert any kind of iterable object into list, array mean numpy array
- by default it takes int types
- dtype can be mentioned as per need

In [248]:
interger = np.array([2,3,5,6,23,56,58])  # default integer
interger

array([ 2,  3,  5,  6, 23, 56, 58])

In [249]:
defined_integer = np.array([2,3,4,5,5,50,75,80,80], dtype=np.int64)   # mention dtype as int64
defined_integer

array([ 2,  3,  4,  5,  5, 50, 75, 80, 80], dtype=int64)

In [250]:
float = np.array([2,3,4,5,5,50,75,80,80], dtype=np.float64)  # mention dtype as float64
float

array([ 2.,  3.,  4.,  5.,  5., 50., 75., 80., 80.])

In [251]:
bool = np.array([True, False, True, True, False], dtype=np.bool8)  # dtype as boolean
bool

array([ True, False,  True,  True, False])

In [252]:
empty = np.empty([3,3], dtype=np.complex64)
empty

array([[0.+2.j       , 0.+2.125j    , 0.+2.25j     ],
       [0.+2.3125j   , 0.+2.3125j   , 0.+3.140625j ],
       [0.+3.2929688j, 0.+3.3125j   , 0.+3.3125j   ]], dtype=complex64)

In [253]:
string = np.array(['apple','orange', 'banana', 'grapes'], dtype=np.string_)  # string type, mentioning dtype is recommended
string

array([b'apple', b'orange', b'banana', b'grapes'], dtype='|S6')

# NDarray Object Inspection

- ndim : there is function that is 'ndim' by which we can extract/ find dimention
- shape : by which we can know the shape (number of rows & columns)
- In NDarray object Inspection, type(ndim), shape is very important

In [254]:
string.ndim

1

In [255]:
empty

array([[0.+2.j       , 0.+2.125j    , 0.+2.25j     ],
       [0.+2.3125j   , 0.+2.3125j   , 0.+3.140625j ],
       [0.+3.2929688j, 0.+3.3125j   , 0.+3.3125j   ]], dtype=complex64)

In [256]:
empty.ndim  # lets verify the the empty output, there a two bracket inside array or array inside array, value as per rows & columns

2

In [257]:
empty.shape  # In order to verify the number of rows & columns

(3, 3)

In [258]:
interger

array([ 2,  3,  5,  6, 23, 56, 58])

In [259]:
interger.shape  # 7 value with 1 dimension

(7,)

In [260]:
empty.itemsize # Represent the byte size of each item
string.itemsize

6

In [261]:
string.item(0) # checking index value, we can fetch data more easily

b'apple'

In [262]:
bool

array([ True, False,  True,  True, False])

In [263]:
bool.any()  # Check & verify wheter any true in bool variable, its returning true becasue of lots of true available in bool

True

In [264]:
bool.all() # Check whether all true or not. .any & .all function basically applied on boolean value

False

In [265]:
string.T # Transpose its not properloy understandable because of 1D, it will more clear when apply on 2D

array([b'apple', b'orange', b'banana', b'grapes'], dtype='|S6')

In [266]:
# Checking Data type
empty.dtype

dtype('complex64')

In [267]:
interger.dtype

dtype('int32')

In [268]:
interger.itemsize

4

In [269]:
# We can directly inspect data type from here & depending on that we can decide what kind of steps to be applied for this.becasue we cant run numerical operation on str, so this will help to first understand
string.dtype  

dtype('S6')

In [270]:
empty.size # to know the total number of elements. empty is 3x3 matrix so total 9 elements

9

- So, up to this we can slice & fetch, but there is another method by which we can do it more efficiently, that is more efficient than list slicing

# Slicing

In [271]:
arr = np.array(
    [
        [44, 22, 56],   # 1st Index
        [67, 76, 89],   # 2nd Index
        [52, 45, 78]    # 3rd Index
    ]
)

### General Indexing

In [272]:
arr[0] # First Index Value
arr[1] # 2nd index value
arr[2] # 3rd index value


array([52, 45, 78])

In [273]:
arr[0][0] # First Index first value
arr[0][1] # First Index 2nd Value
arr[0][2] # First Index 3rd Value

56

In [274]:
arr[1][0] # 2nd Index 1st value
arr[1][1] # 2nd Index 2nd value
arr[1][2] # 2nd Index 3rd value

89

In [275]:
arr[2][0] # 3rd index 1st Value
arr[2][1] # 3rd index 2nd Value
arr[2][2] # 3rd index 3rd Value

78

### Alternative Indexing

In [276]:
arr  

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

In [277]:
arr[0][0] # General Indexing for 1st index 1st value

44

In [278]:
arr[0,0] # Alterative indexing for 1st index 1st value

44

In [279]:
arr[0][1] # 1st index, 2nd value
arr[0,1] # 1st index, 2nd value- Alternative

22

In [280]:
arr [0] [2] # 1st index, 3rd value
arr [0,2] # 1st index, 3rd value - Alternative

56

In [281]:
arr[1] [1] # 2nd index, 2nd value
arr [1, 1] # 2nd index, 2nd value- Alternative

76

In [282]:
arr [1] [0] # 2nd index, 1st Value
arr [1,0] # 2nd index, 1st value

67

In [283]:
arr # review

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

In [284]:
arr[1] [2] # 2nd index, 3rd value
arr [1,2] # 2nd index, 3rd value- Alternative

89

In [285]:
arr [2] [0] # 3rd index, 1st value
arr [2,0]

52

In [286]:
arr[2][1] # 3rd index, 2nd value
arr[2,1] # 3rd index, 2nd value- Alternative

45

In [287]:
arr[2] [2] # 3rd index, 3rd value
arr [2,2] # 3rd index, 3rd value- Alternative

78

In [288]:
arr 

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

In [289]:
arr[0] # First Index Value/ 1st full row
arr[:,0] # First Index Value/ 1st full row - Alternative

array([44, 67, 52])

In [290]:
arr[1] # 2nd Index Value/ full row
arr[:,1]

array([22, 76, 45])

In [291]:
arr[1]

array([67, 76, 89])

In [292]:
arr[2]

array([52, 45, 78])

In [293]:
arr[:,0] # all rows: 1st column

array([44, 67, 52])

In [294]:
arr[:,1] # all rows: 2nd column, comma means numpy

array([22, 76, 45])

In [295]:
arr

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

In [296]:
arr[:,2] # all rows: 3rd column

array([56, 89, 78])

In [297]:
arr[:] # All

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

In [298]:
arr[:,] # All Alternaive

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

### Array 2 Practice

In [299]:
arr2 = np.array(
    [
        [44, 22, 56, 71],   # 1st Index
        [67, 76, 89, 72],   # 2nd Index
        [52, 45, 78, 73],   # 3rd Index
    ]
)

In [300]:
arr2[0,:]   # as per matrix, 0 is for row and : (colon) is for columns e.g all columns

array([44, 22, 56, 71])

In [301]:
arr2[1,:] # 2nd row, all columns

array([67, 76, 89, 72])

In [302]:
arr2[2,:] # 3rd row/index, all columns

array([52, 45, 78, 73])

In [303]:
arr2[0,:1] # firs row, first value

array([44])

In [304]:
arr2[0,:2] # first row, first 2 values

array([44, 22])

In [305]:
arr2[0,:3] # first row, first 3 values

array([44, 22, 56])

In [306]:
arr2[0,:4] # first row, first 4 values

array([44, 22, 56, 71])

In [307]:
arr2[0,:] # first row, first 4 values- Alternative

array([44, 22, 56, 71])

In [308]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [309]:
arr2[1,:1] # 2nd row, 1st value

array([67])

In [310]:
arr2[1,:2] # 2nd row, 1st 2 values

array([67, 76])

In [311]:
arr2[1,:3] # 2nd row, first 3 values

array([67, 76, 89])

In [312]:
arr2[1,:4] # 2nd row, fist 3 values

array([67, 76, 89, 72])

In [313]:
arr2[1,:] # 2nd row, fist 3 values- Alternative

array([67, 76, 89, 72])

In [314]:
arr2[2,:1] # 3rd row, 1 st value
arr2[2,:2] # 3rd row, first 2 st values
arr2[2,:3] # 3rd row, first 3 st values
arr2[2,:4] # 3rd row, first 4 st values
arr2[2,:]  # 3rd row, first 4 st values- Alternative

array([52, 45, 78, 73])

In [315]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [316]:
arr2[0, 0:1] # 1st row, 1st index, 1st value

array([44])

In [317]:
arr2[0,0:2] # 1st row, 1st to 2nd value

array([44, 22])

In [318]:
arr2[0, 0:3] # 1st row, 1st to 3rd value

array([44, 22, 56])

In [319]:
arr2 [0, 0:4] # # 1st row, 1st to 3rd value

array([44, 22, 56, 71])

In [320]:
arr2 [2, 1:3]  # 3rd index/row, 2nd to 3rd value

array([45, 78])

In [321]:
arr2[2, 2:4] # 3rd index/ row, 3rd to 4th value

array([78, 73])

In [322]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [323]:
arr2[0, 1:3] # 1st index/row, 2nd to 3rd value

array([22, 56])

In [324]:
arr2[1, 1:3] # 2nd index/ row,, 2nd to 3rd value

array([76, 89])

In [325]:
arr2[1, 2:4]  # 2nd index/ row, 3rd to 4th value

array([89, 72])

In [326]:
arr2[2, 2:4] # 3rd index/ value, 3rd to 4th value

array([78, 73])

In [327]:
arr2 [2, 1:4] # 3rd index/ value, 2nd to 4th value

array([45, 78, 73])

In [328]:
arr2[2, 1:3] # 3rd index/ value, 2nd to 3rd value

array([45, 78])

### Applying step size into indexcing

In [329]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [330]:
arr2[0, 0:4:2]  # 1st row/ index, 1st to 4th value with 2 step in size  [0 to 4, 2 is step size]

array([44, 56])

In [331]:
arr2[0, 0:4:3] # 1st row/ index, 1st to 4th value with 3 step in size

array([44, 71])

In [332]:
arr2[1, 0:4:2] # 2nd row/ index, 1st to 4th value with 2 step in size

array([67, 89])

In [333]:
arr2[1, 0:4:3] # 2nd row/ index, 1st to 4th value with 3 step in size

array([67, 72])

In [334]:
arr2[2, 0:4:2] # 3rd row/ index, 1st to 4th value with 2 step in size

array([52, 78])

In [335]:
arr2[:]  # All rows : all columns

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [336]:
arr2[:, 0:4:2] # : means all rows, 0 to 4th with 2 in step size

array([[44, 56],
       [67, 89],
       [52, 78]])

In [337]:
arr2[:, 0:4:3]

array([[44, 71],
       [67, 72],
       [52, 73]])

In [338]:
arr2[:, 1:3] # Middle 2 rows & columns

array([[22, 56],
       [76, 89],
       [45, 78]])

In [339]:
arr2[1:, 0:4:2]  # 2nd index/ row 0 to 4th columns with 2 in step size

array([[67, 89],
       [52, 78]])

In [340]:
arr2[2:, 0:4:2] # 3rd index/ row , 0 to 4th columns with 2 in step size

array([[52, 78]])

In [341]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [342]:
arr2[1:, 0:4:2]

array([[67, 89],
       [52, 78]])

In [343]:
arr2[1:, 1:4:2] # 2nd index/ row; 1 to 4th columns, 2 in step size

array([[76, 72],
       [45, 73]])

In [344]:
arr2[0:, 1:4:2] # 1st index/ row, 1 to 4th columns with 2 in step size

array([[22, 71],
       [76, 72],
       [45, 73]])

In [345]:
arr2[1:, 1:3] # 2nd index/ row, 1 to 3rd colum, In such way using comma, we can fetch multi dimentional arrays

array([[76, 89],
       [45, 78]])

In [346]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [347]:
arr2[1:3:2, 0:4:2] # 2nd row/ index: 1 to 3 columns 2 in step size,  1 to 4 colums with step 2 in size

array([[67, 89]])

In [348]:
arr2[1:, 2:4] # 2nd row/ index; 3 to 4 th columns

array([[89, 72],
       [78, 73]])

In [349]:
arr2[1:, 2:] # 2nd row/ index; 3 to 4 th columns- Alternative

array([[89, 72],
       [78, 73]])

In [350]:
arr3 = np.array(
    [
        [44, 22, 45, 33],
        [34, 45, 40, 32],
        [12, 56, 80, 90],
        [50, 40, 60, 70]
    ]
)

In [351]:
arr3[1:3:, 1:3] # Middle 4 value, 2nd & 3rd row:, 2nd to 3rd colums.  1:3 Dimenstion One, 1:3 Dimenstion Two

array([[45, 40],
       [56, 80]])

In [352]:
arr3[1:3:, 1:]   # 2nd to 3rd rows:, 2 to last all columns

array([[45, 40, 32],
       [56, 80, 90]])

In [353]:
arr3[2:, 1:]  # from 3rd all rows, 2nd to last all columns

array([[56, 80, 90],
       [40, 60, 70]])

In [357]:
arr3[2:, 1:3] # from 3rd all rows 2 to 3rd colums

array([[56, 80],
       [40, 60]])

In [355]:
arr3[1:, 2:]

array([[40, 32],
       [80, 90],
       [60, 70]])

In [356]:
arr3 [1:2:, 1:2]

array([[45]])