# Numpy

- Import Numpy
- Mathmatical Operations
- Array Creation
- Adding Dimension
- np.zeros
- np.eye
- np.empty
- np.full
- np.arange   / array range
- np.linspace  (differnce between arange & linspace)
- random & randomn, randint
- Types of Array

In [1]:
import numpy as np
np.__version__

'1.23.3'

# Math Computational

In [2]:
summ = 0
for num in range(1, 9999999):
    summ += num**2*3

summ

999999550000064999997

In [3]:
np.arange(1,9999999)

array([      1,       2,       3, ..., 9999996, 9999997, 9999998])

## Comparing Computational efficiency between general & numpy

In [4]:
# General Python, takes more time
summ1 = 0
for num in range (1,99999999):
    summ1 += num

summ1

4999999850000001

In [5]:
# Numpy sum operation     takes less time, in case of huge data we will see the different more clearly
np.sum(np.arange(1,99999999, dtype=np.int64))

4999999850000001

In [6]:
np.arange(99999999, dtype=np.int64).sum()   # alternative syntax of doing sum aggregation over numpy

4999999850000001

### Numpy is more efficinet
- Previous one needs more time than numpy
- for this operation, numpy is not taking for loop, while for same general python using loop

# Array Creation

In [7]:
# np.zeros([shape size] comma dtype with np.bit size)  # Syntax
np.zeros([3,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [8]:
np.zeros([5,5], dtype=np.int64)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [9]:
np.zeros([4, 4], dtype=np.float64)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros([2,2], dtype=np.float16)

array([[0., 0.],
       [0., 0.]], dtype=float16)

In [11]:
np.zeros([4,3], dtype=np.int64)  # rows & columns is 4:3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [12]:
np.zeros([5,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

### Adding Demension

In [13]:
np.zeros([4,3,2], dtype=np.int64)  
# 4 rows, 3 columns and 2 cell/value per row  or for each row, here is adding dimenstion as 2

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=int64)

In [14]:
np.zeros([4,3,3], dtype=np.int64)    # 3 cell/ value per row

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [15]:
np.zeros([4,3,4], dtype=np.int64)    # 4 cell/ value per row

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)

In [16]:
np.zeros([4,3,5], dtype=np.int64)    # 5 cell/ value per row

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [17]:
np.zeros([4,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [18]:
np.zeros([4,5,10], dtype=np.int64)   # 10 dimension

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [19]:
np.zeros([4,8,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0

In [20]:
np.zeros([4,3,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [21]:
np.zeros([4,2,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [22]:
np.ones([4,4])    # by default dtype takes float & mentioning dtype is optional

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.ones([4,4], dtype=np.float64)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.ones([4,4], dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [25]:
np.eye(3,3)     # np.eye means "Identity Matrix", eye operation will not take square bracket [], np.eye takes only "tuple"

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(3,3, k=1)    # by default k = 0

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [27]:
np.eye(6,6)       # default k = 0

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [28]:
np.eye(6,6, k=0)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [29]:
np.eye(6,6, k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.eye(6,6, k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
np.eye(6,6, k=4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.eye(6,6, k=-4)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [33]:
np.eye(6,6, k=5)

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.eye(3,3, k=-1) 

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [35]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [36]:
np.eye(3,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [37]:
np.eye(3,4,-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [38]:
np.eye(3,4,3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.eye(3,4,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.empty([3,3])

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [41]:
np.empty([3,3,3])

array([[[6.23042070e-307, 4.22795269e-307, 1.33511969e-306],
        [2.22522868e-306, 1.24611266e-306, 1.78017181e-306],
        [6.23061763e-307, 1.06811422e-306, 4.45033870e-308]],

       [[1.33511969e-306, 3.22651328e-307, 1.11260755e-306],
        [3.11515773e-307, 1.33512173e-306, 6.23055651e-307],
        [1.69119194e-306, 6.23060744e-307, 6.23053954e-307]],

       [[9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
        [1.86921143e-306, 6.23061763e-307, 9.34593493e-307],
        [7.56602524e-307, 2.22522596e-306, 2.56765117e-312]]])

In [42]:
np.empty([3,3,2])

array([[[1.37962049e-306, 1.24610791e-306],
        [1.11260959e-306, 1.69109959e-306],
        [9.34603679e-307, 1.42419802e-306]],

       [[1.78019082e-306, 4.45061456e-308],
        [1.24612081e-306, 1.37962049e-306],
        [9.34597567e-307, 1.29061821e-306]],

       [[1.78019625e-306, 1.11255866e-306],
        [8.90098127e-307, 9.34609790e-307],
        [3.91792279e-317, 4.47593775e-091]]])

In [43]:
np.empty([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [44]:
np.full([3,3], 8.5)   # it will fill the 3x3 matrix with 8.5

array([[8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5]])

In [45]:
np.full([3,3], 10.5)

array([[10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5]])

### Arange

- np.arange will not take squre backet
- mentioning dtype is optional
- it will take (start: end: step size)
- default takes int
- float & int can be mentioned in dtype
- its like a range function
- it can be reshaped

In [46]:
np.arange(1,100)   

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [47]:
np.arange(1,100, dtype=np.int64) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int64)

In [48]:
np.arange(1,100, dtype=np.float64) 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 65.,
       66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77., 78.,
       79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91.,
       92., 93., 94., 95., 96., 97., 98., 99.])

In [49]:
np.arange(1,100,5)    # step size = 5

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [50]:
np.arange(0,100,5) 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [51]:
np.linspace(1,10, 500)  # in a range 1 to 10 , it will return 500 random values

array([ 1.        ,  1.01803607,  1.03607214,  1.05410822,  1.07214429,
        1.09018036,  1.10821643,  1.12625251,  1.14428858,  1.16232465,
        1.18036072,  1.19839679,  1.21643287,  1.23446894,  1.25250501,
        1.27054108,  1.28857715,  1.30661323,  1.3246493 ,  1.34268537,
        1.36072144,  1.37875752,  1.39679359,  1.41482966,  1.43286573,
        1.4509018 ,  1.46893788,  1.48697395,  1.50501002,  1.52304609,
        1.54108216,  1.55911824,  1.57715431,  1.59519038,  1.61322645,
        1.63126253,  1.6492986 ,  1.66733467,  1.68537074,  1.70340681,
        1.72144289,  1.73947896,  1.75751503,  1.7755511 ,  1.79358717,
        1.81162325,  1.82965932,  1.84769539,  1.86573146,  1.88376754,
        1.90180361,  1.91983968,  1.93787575,  1.95591182,  1.9739479 ,
        1.99198397,  2.01002004,  2.02805611,  2.04609218,  2.06412826,
        2.08216433,  2.1002004 ,  2.11823647,  2.13627255,  2.15430862,
        2.17234469,  2.19038076,  2.20841683,  2.22645291,  2.24

##### arange return value within a range with or without step size, linspace return values in a range with asked number of values to be returned

In [52]:
np.random.randint(2,4)

3

In [53]:
np.random.randint(2,10)

9

In [54]:
np.random.randn(50)   # As I want 50 random value

array([ 6.09147632e-01,  6.27445692e-01,  1.37676712e-02, -2.05636463e+00,
        2.31612573e+00, -9.26127427e-02,  5.06265152e-01,  4.03299091e-01,
        1.23917024e+00,  1.52447485e+00, -6.40999947e-01,  8.46143236e-01,
       -1.12817764e+00,  2.47189220e-01, -5.10086836e-01,  3.25133426e-01,
        1.70062389e+00,  7.74110102e-03, -3.86130359e-01,  7.85950118e-04,
       -2.38369783e-01, -4.44152035e-01,  2.67564383e-01,  2.39850671e-01,
       -9.14380803e-01,  9.79028375e-01,  7.31836979e-01, -7.81685947e-01,
       -2.03854805e+00,  1.35093579e-02,  9.62724560e-01, -2.16381687e+00,
        2.37073397e-01, -1.23459354e+00,  3.21685399e-01,  4.67213207e-01,
       -3.15387347e-01, -2.89352225e-03,  1.96889184e-02, -8.52243537e-01,
       -5.36856831e-01, -9.18030538e-02, -9.17818366e-01,  4.23215311e-01,
       -5.88786466e-01,  6.21431388e-01,  1.90512630e-01, -4.76190853e-01,
       -7.26980344e-01, -4.51413975e-01])

In [55]:
np.random.randn(1,15, 5) 

array([[[ 0.47338683,  1.99393522,  1.43234773, -0.18974969,
          0.2776429 ],
        [-0.58174179,  0.56491836,  0.30451888,  0.75034267,
          0.54904902],
        [ 0.31502909,  0.68463214, -1.12041901,  1.20996682,
         -1.70196797],
        [ 1.01768375, -1.05373547, -0.1309687 , -0.07557671,
          0.25802009],
        [ 1.21326903, -0.4789054 , -0.89249773, -0.96264318,
         -0.45373253],
        [-1.58760949, -0.63782876,  1.73256206, -0.41022293,
          0.84580059],
        [-0.08340396, -0.9805258 , -0.98265034,  0.71298404,
         -0.41450267],
        [-0.95502304, -2.2552376 , -0.15169314, -1.04738939,
         -0.35297622],
        [ 1.28799324,  0.31141257, -1.2642409 , -0.31421972,
          2.25001553],
        [ 0.42955606, -0.23036497, -0.62515697,  1.09477007,
         -1.16078784],
        [-0.52336506,  1.77553294, -0.38347204,  0.11165748,
         -0.94621422],
        [-1.06224349, -1.03183188,  1.14194716,  1.63021417,
         -0.378

# Types of Array

- Convert any kind of iterable object into list, array mean numpy array
- by default it takes int types
- dtype can be mentioned as per need

In [57]:
np.array([2,3,5,6,23,56,58]) 

array([ 2,  3,  5,  6, 23, 56, 58])

In [61]:
np.array([2,3,4,5,5,50,75,80,80], dtype=np.int64)   # nmention dtype as int64

array([ 2,  3,  4,  5,  5, 50, 75, 80, 80], dtype=int64)

In [62]:
np.array([2,3,4,5,5,50,75,80,80], dtype=np.float64)  # nmention dtype as float64

array([ 2.,  3.,  4.,  5.,  5., 50., 75., 80., 80.])

In [63]:
np.array([True, False, True, True, False], dtype=np.bool8)  # dtype as boolean

array([ True, False,  True,  True, False])

In [65]:
np.empty([3,3], dtype=np.complex64)

array([[0.+2.j       , 0.+2.125j    , 0.+2.25j     ],
       [0.+2.3125j   , 0.+2.3125j   , 0.+3.140625j ],
       [0.+3.2929688j, 0.+3.3125j   , 0.+3.3125j   ]], dtype=complex64)

In [67]:
np.array(['apple','orange', 'banana', 'grapes'], dtype=np.string_)  # string type, mentioning dtype is recommended

array([b'apple', b'orange', b'banana', b'grapes'], dtype='|S6')