# Numpy

- Import Numpy
- Mathmatical Operations
- Array Creation
- Adding Dimension
- np.zeros
- np.eye
- np.empty
- np.full
- np.arange   / array range
- np.linspace  (differnce between arange & linspace)
- random & randomn, randint

In [1]:
import numpy as np
np.__version__

'1.23.3'

# Math Computational

In [2]:
summ = 0
for num in range(1, 9999999):
    summ += num**2*3

summ

999999550000064999997

In [3]:
np.arange(1,9999999)

array([      1,       2,       3, ..., 9999996, 9999997, 9999998])

## Comparing Computational efficiency between general & numpy

In [4]:
# General Python, takes more time
summ1 = 0
for num in range (1,99999999):
    summ1 += num

summ1

4999999850000001

In [5]:
# Numpy sum operation     takes less time, in case of huge data we will see the different more clearly
np.sum(np.arange(1,99999999, dtype=np.int64))

4999999850000001

In [6]:
np.arange(99999999, dtype=np.int64).sum()   # alternative syntax of doing sum aggregation over numpy

4999999850000001

### Numpy is more efficinet
- Previous one needs more time than numpy
- for this operation, numpy is not taking for loop, while for same general python using loop

# Array Creation

In [12]:
# np.zeros([shape size] comma dtype with np.bit size)  # Syntax
np.zeros([3,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [9]:
np.zeros([5,5], dtype=np.int64)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [13]:
np.zeros([4, 4], dtype=np.float64)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros([2,2], dtype=np.float16)

array([[0., 0.],
       [0., 0.]], dtype=float16)

In [16]:
np.zeros([4,3], dtype=np.int64)  # rows & columns is 4:3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [17]:
np.zeros([5,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

### Adding Demension

In [18]:
np.zeros([4,3,2], dtype=np.int64)  
# 4 rows, 3 columns and 2 cell/value per row  or for each row, here is adding dimenstion as 2

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=int64)

In [19]:
np.zeros([4,3,3], dtype=np.int64)    # 3 cell/ value per row

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [25]:
np.zeros([4,3,4], dtype=np.int64)    # 4 cell/ value per row

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)

In [23]:
np.zeros([4,3,5], dtype=np.int64)    # 5 cell/ value per row

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [24]:
np.zeros([4,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [27]:
np.zeros([4,5,10], dtype=np.int64)   # 10 dimension

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [30]:
np.zeros([4,8,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0

In [28]:
np.zeros([4,3,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [29]:
np.zeros([4,2,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [34]:
np.ones([4,4])    # by default dtype takes float & mentioning dtype is optional

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.ones([4,4], dtype=np.float64)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.ones([4,4], dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [38]:
np.eye(3,3)     # np.eye means "Identity Matrix", eye operation will not take square bracket [], np.eye takes only "tuple"

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.eye(3,3, k=1)    # by default k = 0

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [50]:
np.eye(6,6)       # default k = 0

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [51]:
np.eye(6,6, k=0)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [52]:
np.eye(6,6, k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [53]:
np.eye(6,6, k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [54]:
np.eye(6,6, k=4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [56]:
np.eye(6,6, k=-4)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [55]:
np.eye(6,6, k=5)

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [47]:
np.eye(3,3, k=-1) 

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [39]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [40]:
np.eye(3,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [44]:
np.eye(3,4,-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [41]:
np.eye(3,4,3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.eye(3,4,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
np.empty([3,3])

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [70]:
np.empty([3,3,3])

array([[[8.49069524e-312, 8.00386346e-322, 0.00000000e+000],
        [0.00000000e+000, 1.24611266e-306, 1.15998412e-028],
        [4.31603868e-080, 1.94919985e-153, 1.35717430e+131]],

       [[1.05190653e-153, 1.05191620e-153, 1.05191677e-153],
        [1.05191734e-153, 1.05191791e-153, 1.05191848e-153],
        [1.05191905e-153, 1.05191962e-153, 6.01391519e-154]],

       [[1.05192019e-153, 1.94321996e-109, 4.90900643e+252],
        [1.94918511e-153, 6.32672800e+180, 4.74483502e+170],
        [5.55151217e-048, 1.97229332e-062, 6.80209823e-310]]])

In [71]:
np.empty([3,3,2])

array([[[1.37962049e-306, 1.24610791e-306],
        [1.11260959e-306, 1.69109959e-306],
        [9.34603679e-307, 1.42419802e-306]],

       [[1.78019082e-306, 4.45061456e-308],
        [1.24612081e-306, 1.37962049e-306],
        [9.34597567e-307, 1.29061821e-306]],

       [[1.78019625e-306, 1.11255866e-306],
        [8.90098127e-307, 9.34609790e-307],
        [3.91792279e-317, 8.48798316e-312]]])

In [76]:
np.empty([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[1., 0.],
        [0., 0.]]])

In [77]:
np.full([3,3], 8.5)   # it will fill the 3x3 matrix with 8.5

array([[8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5]])

In [78]:
np.full([3,3], 10.5)

array([[10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5]])

### Arange

- np.arange will not take squre backet
- mentioning dtype is optional
- it will take (start: end: step size)
- default takes int
- float & int can be mentioned in dtype
- its like a range function
- it can be reshaped

In [57]:
np.arange(1,100)   

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [58]:
np.arange(1,100, dtype=np.int64) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int64)

In [60]:
np.arange(1,100, dtype=np.float64) 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 65.,
       66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77., 78.,
       79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91.,
       92., 93., 94., 95., 96., 97., 98., 99.])

In [61]:
np.arange(1,100,5)    # step size = 5

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [62]:
np.arange(0,100,5) 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [63]:
np.linspace(1,10, 500)  # in a range 1 to 10 , it will return 500 random values

array([ 1.        ,  1.01803607,  1.03607214,  1.05410822,  1.07214429,
        1.09018036,  1.10821643,  1.12625251,  1.14428858,  1.16232465,
        1.18036072,  1.19839679,  1.21643287,  1.23446894,  1.25250501,
        1.27054108,  1.28857715,  1.30661323,  1.3246493 ,  1.34268537,
        1.36072144,  1.37875752,  1.39679359,  1.41482966,  1.43286573,
        1.4509018 ,  1.46893788,  1.48697395,  1.50501002,  1.52304609,
        1.54108216,  1.55911824,  1.57715431,  1.59519038,  1.61322645,
        1.63126253,  1.6492986 ,  1.66733467,  1.68537074,  1.70340681,
        1.72144289,  1.73947896,  1.75751503,  1.7755511 ,  1.79358717,
        1.81162325,  1.82965932,  1.84769539,  1.86573146,  1.88376754,
        1.90180361,  1.91983968,  1.93787575,  1.95591182,  1.9739479 ,
        1.99198397,  2.01002004,  2.02805611,  2.04609218,  2.06412826,
        2.08216433,  2.1002004 ,  2.11823647,  2.13627255,  2.15430862,
        2.17234469,  2.19038076,  2.20841683,  2.22645291,  2.24

##### arange return value within a range with or without step size, linspace return values in a range with asked number of values to be returned

In [79]:
np.random.randint(2,4)

3

In [80]:
np.random.randint(2,10)

2

In [81]:
np.random.randn(50)   # As I want 50 random value

array([ 0.43829168, -0.69421473, -1.4037175 , -0.50649891, -0.26636377,
       -0.32190746,  1.12826272, -1.35367063, -0.82207224,  1.15716056,
        0.66589272, -0.22285287,  0.1033421 , -0.57118861,  1.21622418,
       -0.4465972 ,  1.38728656, -1.2205693 ,  0.29351254, -0.09537146,
       -0.62482166,  0.64330209, -0.46895725, -0.58131762, -0.4778412 ,
       -0.84715574, -0.62597393, -1.56516762,  0.69906524,  0.46528016,
        0.36687291, -0.29424859, -0.76159797,  0.03799848,  0.17254661,
       -0.2033976 , -1.92275799, -0.82582205,  1.5798812 ,  0.77693237,
       -0.95163655,  0.3731069 , -0.65217848, -0.85430337, -1.07063892,
        0.9450016 , -0.54875689,  0.50214878, -0.67540119, -1.13487617])

In [82]:
np.random.randn(1,15, 5) 

array([[[-0.25750016, -1.26900066,  0.26386189, -0.46475854,
         -0.51796545],
        [-1.44651731,  2.05792258, -0.26503134, -0.05778839,
          0.08611931],
        [ 0.33599323,  0.67775326,  0.08872581, -0.83694521,
          0.44893487],
        [ 1.87033675, -0.2461379 , -2.29241071, -0.74158746,
          0.58560455],
        [-1.76142618,  2.46689238,  1.00919716, -1.23121562,
         -0.7556038 ],
        [-0.4684197 , -0.38559591, -0.2886442 , -0.57291242,
          0.90567187],
        [-0.5094799 , -0.49803476, -0.87947626,  0.52539517,
         -0.60892754],
        [ 0.08258607, -0.2863742 , -0.8380673 ,  1.92483033,
         -0.13898605],
        [ 2.55197404,  1.46066659, -0.5590749 ,  0.30585207,
         -0.44218484],
        [-0.60973415,  0.65994192,  0.63751013, -0.42643835,
          0.04902575],
        [-1.20029095, -2.47393622, -0.62454736,  0.19352057,
         -0.99548734],
        [-1.47838321,  1.28374086,  0.78978077,  0.04403109,
          0.164