# Numpy

- Import Numpy
- Mathmatical Operations
- Array Creation
- Adding Dimension
- np.zeros
- np.eye
- np.empty
- np.full
- np.arange   / array range
- np.linspace  (differnce between arange & linspace)
- random & randomn, randint
- Types of Array
- NDarray, item, itemsize
- Slicing
- Filtering
- Operator
- Matrix Operation
- Load & Save Numpy Array
- Statistical Operations

In [1]:
import numpy as np
np.__version__

'1.23.3'

# Math Computational

In [2]:
summ = 0
for num in range(1, 9999999):
    summ += num**2*3

summ

999999550000064999997

In [3]:
np.arange(1,9999999)

array([      1,       2,       3, ..., 9999996, 9999997, 9999998])

## Comparing Computational efficiency between general & numpy

In [4]:
# General Python, takes more time
summ1 = 0
for num in range (1,99999999):
    summ1 += num

summ1

4999999850000001

In [5]:
# Numpy sum operation     takes less time, in case of huge data we will see the different more clearly
np.sum(np.arange(1,99999999, dtype=np.int64))

4999999850000001

In [6]:
np.arange(99999999, dtype=np.int64).sum()   # alternative syntax of doing sum aggregation over numpy

4999999850000001

In [7]:
np.sum(np.arange(2,5, dtype=np.int64))   # it will take 2 to 4 so (2+3+4 = 9)

9

In [8]:
np.arange(2,5, dtype=np.int64).sum() # Alternative

9

### Numpy is more efficinet
- Previous one needs more time than numpy
- for this operation, numpy is not taking for loop, while for same general python using loop

# Array Creation

In [9]:
# np.zeros([shape size] comma dtype with np.bit size)  # Syntax
np.zeros([3,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [10]:
np.zeros([5,5], dtype=np.int64)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [11]:
np.zeros([4, 4], dtype=np.float64)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.zeros([2,2], dtype=np.float16)

array([[0., 0.],
       [0., 0.]], dtype=float16)

In [13]:
np.zeros([4,3], dtype=np.int64)  # rows & columns is 4:3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [14]:
np.zeros([5,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

### Adding Demension

In [15]:
np.zeros([4,3,2], dtype=np.int64)  
# 4 rows, 3 columns and 2 cell/value per row  or for each row, here is adding dimenstion as 2

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=int64)

In [16]:
np.zeros([4,3,3], dtype=np.int64)    # 3 cell/ value per row

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [17]:
np.zeros([4,3,4], dtype=np.int64)    # 4 cell/ value per row

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)

In [18]:
np.zeros([4,3,5], dtype=np.int64)    # 5 cell/ value per row

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [19]:
np.zeros([4,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [20]:
np.zeros([4,5,10], dtype=np.int64)   # 10 dimension

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [21]:
np.zeros([4,8,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0

In [22]:
np.zeros([4,3,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [23]:
np.zeros([4,2,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [24]:
np.ones([4,4])    # by default dtype takes float & mentioning dtype is optional

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.ones([4,4], dtype=np.float64)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.ones([4,4], dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [27]:
np.eye(3,3)     # np.eye means "Identity Matrix", eye operation will not take square bracket [], np.eye takes only "tuple"

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(3,3, k=1)    # by default k = 0

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [29]:
np.eye(6,6)       # default k = 0

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
np.eye(6,6, k=0)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [31]:
np.eye(6,6, k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.eye(6,6, k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.eye(6,6, k=4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.eye(6,6, k=-4)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [35]:
np.eye(6,6, k=5)

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
np.eye(3,3, k=-1) 

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [37]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [38]:
np.eye(3,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [39]:
np.eye(3,4,-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [40]:
np.eye(3,4,3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.eye(3,4,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.empty([3,3])

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [43]:
np.empty([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
np.empty([3,3,2])

array([[[4.45619681e+252, 4.37380393e+156],
        [3.16389010e+021, 3.77269378e+233],
        [3.91625961e+156, 1.74926654e+243]],

       [[2.08011909e-115, 3.44380673e-086],
        [5.10112973e+160, 2.38685156e-309],
        [1.55739040e+296, 2.02556196e+174]],

       [[5.28555514e+180, 2.31274374e-152],
        [5.28626956e-085, 2.26432613e+285],
        [1.86927594e-152, 1.27617599e-152]]])

In [45]:
np.empty([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [46]:
np.full([3,3], 8.5)   # it will fill the 3x3 matrix with 8.5

array([[8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5]])

In [47]:
np.full([3,3], 10.5)

array([[10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5]])

### Arange

- np.arange will not take squre backet
- mentioning dtype is optional
- it will take (start: end: step size)
- default takes int
- float & int can be mentioned in dtype
- its like a range function
- it can be reshaped

In [48]:
np.arange(1,100)   

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
np.arange(1,100, dtype=np.int64) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int64)

In [50]:
np.arange(1,100, dtype=np.float64) 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 65.,
       66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77., 78.,
       79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91.,
       92., 93., 94., 95., 96., 97., 98., 99.])

In [51]:
np.arange(1,100,5)    # step size = 5

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [52]:
np.arange(0,100,5) 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [53]:
np.linspace(1,10, 500)  # in a range 1 to 10 , it will return 500 random values

array([ 1.        ,  1.01803607,  1.03607214,  1.05410822,  1.07214429,
        1.09018036,  1.10821643,  1.12625251,  1.14428858,  1.16232465,
        1.18036072,  1.19839679,  1.21643287,  1.23446894,  1.25250501,
        1.27054108,  1.28857715,  1.30661323,  1.3246493 ,  1.34268537,
        1.36072144,  1.37875752,  1.39679359,  1.41482966,  1.43286573,
        1.4509018 ,  1.46893788,  1.48697395,  1.50501002,  1.52304609,
        1.54108216,  1.55911824,  1.57715431,  1.59519038,  1.61322645,
        1.63126253,  1.6492986 ,  1.66733467,  1.68537074,  1.70340681,
        1.72144289,  1.73947896,  1.75751503,  1.7755511 ,  1.79358717,
        1.81162325,  1.82965932,  1.84769539,  1.86573146,  1.88376754,
        1.90180361,  1.91983968,  1.93787575,  1.95591182,  1.9739479 ,
        1.99198397,  2.01002004,  2.02805611,  2.04609218,  2.06412826,
        2.08216433,  2.1002004 ,  2.11823647,  2.13627255,  2.15430862,
        2.17234469,  2.19038076,  2.20841683,  2.22645291,  2.24

##### arange return value within a range with or without step size, linspace return values in a range with asked number of values to be returned

In [54]:
np.random.randint(2,4)

2

In [55]:
np.random.randint(2,10)

2

In [56]:
np.random.randn(50)   # As I want 50 random value

array([-0.11420421,  2.05638101, -0.13326628,  0.75028141, -0.20394304,
        0.27787811, -0.66076691,  1.41524566,  0.95371593,  0.76525043,
        1.0001211 , -0.71454141,  0.12950556, -2.19254637, -0.70355027,
       -0.26371192,  0.40080946, -0.99433599,  1.13051521, -0.38900311,
        0.73898777,  0.88605239,  0.24280092, -2.56366788, -0.96904614,
       -0.46905484, -0.51255637, -0.37911181, -0.01420357,  1.47728787,
       -0.41329568, -1.33462178,  1.86954266, -0.22959993, -0.60593319,
       -1.20015641, -0.36883402,  1.47602807,  1.48240301,  0.63418771,
        0.07823248, -0.06264729,  0.06426097, -0.27241652,  1.10234793,
        0.83189499, -0.32877165,  0.41180811,  0.75792898,  0.42730054])

In [57]:
np.random.randn(1,15, 5) 

array([[[-0.41285515,  0.11519824, -2.30381348, -1.88227638,
          0.40487689],
        [-0.68332714,  0.75467504, -2.26446665,  0.03342429,
          1.96095672],
        [-3.11556425,  1.93488358,  1.22920802, -1.71196865,
          1.10503659],
        [ 0.59651609, -0.32553952,  0.39602171,  2.52296378,
          0.27428421],
        [-1.1509817 ,  0.75959702, -0.45326502, -0.36176805,
          0.26401802],
        [-0.72554767,  0.31396401, -0.24523759,  0.02399026,
         -0.79736363],
        [ 2.26274352,  0.50244171, -1.15134558,  1.10136372,
          0.04032077],
        [-0.71895927,  0.02062656, -1.72525804, -0.22607864,
          0.12325656],
        [ 0.64419079, -0.26592583, -0.50300627,  0.19238792,
          1.56911002],
        [-1.17852048,  1.9782412 ,  1.11785825,  0.52239554,
         -0.56333623],
        [-0.34827588,  1.72828018, -0.90700111, -0.14829986,
         -0.12082314],
        [-0.88314751,  0.8956322 , -2.23625753,  0.99468531,
         -2.419

# Types of Array

- Convert any kind of iterable object into list, array mean numpy array
- by default it takes int types
- dtype can be mentioned as per need

In [58]:
interger = np.array([2,3,5,6,23,56,58])  # default integer
interger

array([ 2,  3,  5,  6, 23, 56, 58])

In [59]:
defined_integer = np.array([2,3,4,5,5,50,75,80,80], dtype=np.int64)   # mention dtype as int64
defined_integer

array([ 2,  3,  4,  5,  5, 50, 75, 80, 80], dtype=int64)

In [60]:
float = np.array([2,3,4,5,5,50,75,80,80], dtype=np.float64)  # mention dtype as float64
float

array([ 2.,  3.,  4.,  5.,  5., 50., 75., 80., 80.])

In [61]:
bool = np.array([True, False, True, True, False], dtype=np.bool8)  # dtype as boolean
bool

array([ True, False,  True,  True, False])

In [62]:
empty = np.empty([3,3], dtype=np.complex64)
empty

array([[0.+2.j       , 0.+2.125j    , 0.+2.25j     ],
       [0.+2.3125j   , 0.+2.3125j   , 0.+3.140625j ],
       [0.+3.2929688j, 0.+3.3125j   , 0.+3.3125j   ]], dtype=complex64)

In [63]:
string = np.array(['apple','orange', 'banana', 'grapes'], dtype=np.string_)  # string type, mentioning dtype is recommended
string

array([b'apple', b'orange', b'banana', b'grapes'], dtype='|S6')

# NDarray Object Inspection

- ndim : there is function that is 'ndim' by which we can extract/ find dimention
- shape : by which we can know the shape (number of rows & columns)
- In NDarray object Inspection, type(ndim), shape is very important

In [64]:
string.ndim

1

In [65]:
empty

array([[0.+2.j       , 0.+2.125j    , 0.+2.25j     ],
       [0.+2.3125j   , 0.+2.3125j   , 0.+3.140625j ],
       [0.+3.2929688j, 0.+3.3125j   , 0.+3.3125j   ]], dtype=complex64)

In [66]:
empty.ndim  # lets verify the the empty output, there a two bracket inside array or array inside array, value as per rows & columns

2

In [67]:
empty.shape  # In order to verify the number of rows & columns

(3, 3)

In [68]:
interger

array([ 2,  3,  5,  6, 23, 56, 58])

In [69]:
interger.shape  # 7 value with 1 dimension

(7,)

In [70]:
empty.itemsize # Represent the byte size of each item
string.itemsize

6

In [71]:
string.item(0) # checking index value, we can fetch data more easily

b'apple'

In [72]:
bool

array([ True, False,  True,  True, False])

In [73]:
bool.any()  # Check & verify wheter any true in bool variable, its returning true becasue of lots of true available in bool

True

In [74]:
bool.all() # Check whether all true or not. .any & .all function basically applied on boolean value

False

In [75]:
string.T # Transpose its not properloy understandable because of 1D, it will more clear when apply on 2D

array([b'apple', b'orange', b'banana', b'grapes'], dtype='|S6')

In [76]:
# Checking Data type
empty.dtype

dtype('complex64')

In [77]:
interger.dtype

dtype('int32')

In [78]:
interger.itemsize

4

In [79]:
# We can directly inspect data type from here & depending on that we can decide what kind of steps to be applied for this.becasue we cant run numerical operation on str, so this will help to first understand
string.dtype  

dtype('S6')

In [80]:
empty.size # to know the total number of elements. empty is 3x3 matrix so total 9 elements

9

- So, up to this we can slice & fetch, but there is another method by which we can do it more efficiently, that is more efficient than list slicing

# Slicing

In [81]:
arr = np.array(
    [
        [44, 22, 56],   # 1st Index
        [67, 76, 89],   # 2nd Index
        [52, 45, 78]    # 3rd Index
    ]
)

### General Indexing

In [82]:
arr[0] # First Index Value
arr[1] # 2nd index value
arr[2] # 3rd index value


array([52, 45, 78])

In [83]:
arr[0][0] # First Index first value
arr[0][1] # First Index 2nd Value
arr[0][2] # First Index 3rd Value

56

In [84]:
arr[1][0] # 2nd Index 1st value
arr[1][1] # 2nd Index 2nd value
arr[1][2] # 2nd Index 3rd value

89

In [85]:
arr[2][0] # 3rd index 1st Value
arr[2][1] # 3rd index 2nd Value
arr[2][2] # 3rd index 3rd Value

78

### Alternative Indexing

In [86]:
arr  

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

In [87]:
arr[0][0] # General Indexing for 1st index 1st value

44

In [88]:
arr[0,0] # Alterative indexing for 1st index 1st value

44

In [89]:
arr[0][1] # 1st index, 2nd value
arr[0,1] # 1st index, 2nd value- Alternative

22

In [90]:
arr [0] [2] # 1st index, 3rd value
arr [0,2] # 1st index, 3rd value - Alternative

56

In [91]:
arr[1] [1] # 2nd index, 2nd value
arr [1, 1] # 2nd index, 2nd value- Alternative

76

In [92]:
arr [1] [0] # 2nd index, 1st Value
arr [1,0] # 2nd index, 1st value

67

In [93]:
arr # review

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

In [94]:
arr[1] [2] # 2nd index, 3rd value
arr [1,2] # 2nd index, 3rd value- Alternative

89

In [95]:
arr [2] [0] # 3rd index, 1st value
arr [2,0]

52

In [96]:
arr[2][1] # 3rd index, 2nd value
arr[2,1] # 3rd index, 2nd value- Alternative

45

In [97]:
arr[2] [2] # 3rd index, 3rd value
arr [2,2] # 3rd index, 3rd value- Alternative

78

In [98]:
arr 

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

In [99]:
arr[0] # First Index Value/ 1st full row
arr[:,0] # First Index Value/ 1st full row - Alternative

array([44, 67, 52])

In [100]:
arr[1] # 2nd Index Value/ full row
arr[:,1]

array([22, 76, 45])

In [101]:
arr[1]

array([67, 76, 89])

In [102]:
arr[2]

array([52, 45, 78])

In [103]:
arr[:,0] # all rows: 1st column

array([44, 67, 52])

In [104]:
arr[:,1] # all rows: 2nd column, comma means numpy

array([22, 76, 45])

In [105]:
arr

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

In [106]:
arr[:,2] # all rows: 3rd column

array([56, 89, 78])

In [107]:
arr[:] # All

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

In [108]:
arr[:,] # All Alternaive

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

### Array 2 Practice

In [109]:
arr2 = np.array(
    [
        [44, 22, 56, 71],   # 1st Index
        [67, 76, 89, 72],   # 2nd Index
        [52, 45, 78, 73],   # 3rd Index
    ]
)

In [110]:
arr2[0,:]   # as per matrix, 0 is for row and : (colon) is for columns e.g all columns

array([44, 22, 56, 71])

In [111]:
arr2[1,:] # 2nd row, all columns

array([67, 76, 89, 72])

In [112]:
arr2[2,:] # 3rd row/index, all columns

array([52, 45, 78, 73])

In [113]:
arr2[0,:1] # firs row, first value

array([44])

In [114]:
arr2[0,:2] # first row, first 2 values

array([44, 22])

In [115]:
arr2[0,:3] # first row, first 3 values

array([44, 22, 56])

In [116]:
arr2[0,:4] # first row, first 4 values

array([44, 22, 56, 71])

In [117]:
arr2[0,:] # first row, first 4 values- Alternative

array([44, 22, 56, 71])

In [118]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [119]:
arr2[1,:1] # 2nd row, 1st value

array([67])

In [120]:
arr2[1,:2] # 2nd row, 1st 2 values

array([67, 76])

In [121]:
arr2[1,:3] # 2nd row, first 3 values

array([67, 76, 89])

In [122]:
arr2[1,:4] # 2nd row, fist 3 values

array([67, 76, 89, 72])

In [123]:
arr2[1,:] # 2nd row, fist 3 values- Alternative

array([67, 76, 89, 72])

In [124]:
arr2[2,:1] # 3rd row, 1 st value
arr2[2,:2] # 3rd row, first 2 st values
arr2[2,:3] # 3rd row, first 3 st values
arr2[2,:4] # 3rd row, first 4 st values
arr2[2,:]  # 3rd row, first 4 st values- Alternative

array([52, 45, 78, 73])

In [125]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [126]:
arr2[0, 0:1] # 1st row, 1st index, 1st value

array([44])

In [127]:
arr2[0,0:2] # 1st row, 1st to 2nd value

array([44, 22])

In [128]:
arr2[0, 0:3] # 1st row, 1st to 3rd value

array([44, 22, 56])

In [129]:
arr2 [0, 0:4] # # 1st row, 1st to 3rd value

array([44, 22, 56, 71])

In [130]:
arr2 [2, 1:3]  # 3rd index/row, 2nd to 3rd value

array([45, 78])

In [131]:
arr2[2, 2:4] # 3rd index/ row, 3rd to 4th value

array([78, 73])

In [132]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [133]:
arr2[0, 1:3] # 1st index/row, 2nd to 3rd value

array([22, 56])

In [134]:
arr2[1, 1:3] # 2nd index/ row,, 2nd to 3rd value

array([76, 89])

In [135]:
arr2[1, 2:4]  # 2nd index/ row, 3rd to 4th value

array([89, 72])

In [136]:
arr2[2, 2:4] # 3rd index/ value, 3rd to 4th value

array([78, 73])

In [137]:
arr2 [2, 1:4] # 3rd index/ value, 2nd to 4th value

array([45, 78, 73])

In [138]:
arr2[2, 1:3] # 3rd index/ value, 2nd to 3rd value

array([45, 78])

### Applying step size into indexcing

In [139]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [140]:
arr2[0, 0:4:2]  # 1st row/ index, 1st to 4th value with 2 step in size  [0 to 4, 2 is step size]

array([44, 56])

In [141]:
arr2[0, 0:4:3] # 1st row/ index, 1st to 4th value with 3 step in size

array([44, 71])

In [142]:
arr2[1, 0:4:2] # 2nd row/ index, 1st to 4th value with 2 step in size

array([67, 89])

In [143]:
arr2[1, 0:4:3] # 2nd row/ index, 1st to 4th value with 3 step in size

array([67, 72])

In [144]:
arr2[2, 0:4:2] # 3rd row/ index, 1st to 4th value with 2 step in size

array([52, 78])

In [145]:
arr2[:]  # All rows : all columns

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [146]:
arr2[:, 0:4:2] # : means all rows, 0 to 4th with 2 in step size

array([[44, 56],
       [67, 89],
       [52, 78]])

In [147]:
arr2[:, 0:4:3]

array([[44, 71],
       [67, 72],
       [52, 73]])

In [148]:
arr2[:, 1:3] # Middle 2 rows & columns

array([[22, 56],
       [76, 89],
       [45, 78]])

In [149]:
arr2[1:, 0:4:2]  # 2nd index/ row 0 to 4th columns with 2 in step size

array([[67, 89],
       [52, 78]])

In [150]:
arr2[2:, 0:4:2] # 3rd index/ row , 0 to 4th columns with 2 in step size

array([[52, 78]])

In [151]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [152]:
arr2[1:, 0:4:2]

array([[67, 89],
       [52, 78]])

In [153]:
arr2[1:, 1:4:2] # 2nd index/ row; 1 to 4th columns, 2 in step size

array([[76, 72],
       [45, 73]])

In [154]:
arr2[0:, 1:4:2] # 1st index/ row, 1 to 4th columns with 2 in step size

array([[22, 71],
       [76, 72],
       [45, 73]])

In [155]:
arr2[1:, 1:3] # 2nd index/ row, 1 to 3rd colum, In such way using comma, we can fetch multi dimentional arrays

array([[76, 89],
       [45, 78]])

In [156]:
arr2

array([[44, 22, 56, 71],
       [67, 76, 89, 72],
       [52, 45, 78, 73]])

In [157]:
arr2[1:3:2, 0:4:2] # 2nd row/ index: 1 to 3 columns 2 in step size,  1 to 4 colums with step 2 in size

array([[67, 89]])

In [158]:
arr2[1:, 2:4] # 2nd row/ index; 3 to 4 th columns

array([[89, 72],
       [78, 73]])

In [159]:
arr2[1:, 2:] # 2nd row/ index; 3 to 4 th columns- Alternative

array([[89, 72],
       [78, 73]])

In [160]:
arr3 = np.array(
    [
        [44, 22, 45, 33],
        [34, 45, 40, 32],
        [12, 56, 80, 90],
        [50, 40, 60, 70]
    ]
)

In [161]:
arr3[1:3:, 1:3] # Middle 4 value, 2nd & 3rd row:, 2nd to 3rd colums.  1:3 Dimenstion One, 1:3 Dimenstion Two

array([[45, 40],
       [56, 80]])

In [162]:
arr3[1:3:, 1:]   # 2nd to 3rd rows:, 2 to last all columns

array([[45, 40, 32],
       [56, 80, 90]])

In [163]:
arr3[2:, 1:]  # from 3rd all rows, 2nd to last all columns

array([[56, 80, 90],
       [40, 60, 70]])

In [164]:
arr3[2:, 1:3] # from 3rd all rows 2 to 3rd colums

array([[56, 80],
       [40, 60]])

In [165]:
arr3[1:, 2:]

array([[40, 32],
       [80, 90],
       [60, 70]])

In [166]:
arr3 [1:2:, 1:2]

array([[45]])

# Filtering

In [167]:
arr3

array([[44, 22, 45, 33],
       [34, 45, 40, 32],
       [12, 56, 80, 90],
       [50, 40, 60, 70]])

In [168]:
# Find values > 25
arr3 > 25  # Return Boolean

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [169]:
arr3 [arr3 > 25] # Wnen asked to number return, not boolean

array([44, 45, 33, 34, 45, 40, 32, 56, 80, 90, 50, 40, 60, 70])

#### Find values > 50 (Boolean & Number form)

In [170]:
arr3 > 50 # return boolean form

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [False, False,  True,  True]])

In [171]:
arr3[arr3>50] # return in number form

array([56, 80, 90, 60, 70])

#### Find values in two range / condition

In [172]:
# Find values > 50 & < 70 - Using And
arr3 [(arr3>50) & (arr3<70)]  # Square bracket inside first bracket

array([56, 60])

In [173]:
arr

array([[44, 22, 56],
       [67, 76, 89],
       [52, 45, 78]])

#### Find Divisible Number

In [174]:
arr[(arr%2==0) | (arr%3==0)]   # Divisible by 2 or 3

array([44, 22, 56, 76, 52, 45, 78])

In [175]:
arr[(arr%4==0) | (arr%5==0)]  # Divisible by 4 or 5

array([44, 56, 76, 52, 45])

In [176]:
arr[arr%2==0] # Divisibe by 2

array([44, 22, 56, 76, 52, 78])

In [177]:
arr[~arr%2==0]  # Not divisibe by 2, using negation (~) sign

array([67, 89, 45])

# Operator

In [178]:
arr3

array([[44, 22, 45, 33],
       [34, 45, 40, 32],
       [12, 56, 80, 90],
       [50, 40, 60, 70]])

In [179]:
# Get 3 by 3 Metrix over arr3 by doing slicing
arr4 = arr3[1:, 1:]

In [180]:
arr4

array([[45, 40, 32],
       [56, 80, 90],
       [40, 60, 70]])

#### Multiplication, Division with array

- Multiplication / operation applied over list by using loop
- But it is more convenient here

In [181]:
arr4 * 2 # Multiplied 2 with all values

array([[ 90,  80,  64],
       [112, 160, 180],
       [ 80, 120, 140]])

In [182]:
arr4 / 2   # Division  (Float)

array([[22.5, 20. , 16. ],
       [28. , 40. , 45. ],
       [20. , 30. , 35. ]])

In [183]:
arr4 // 2    # Division (interger)

array([[22, 20, 16],
       [28, 40, 45],
       [20, 30, 35]], dtype=int32)

In [184]:
arr4

array([[45, 40, 32],
       [56, 80, 90],
       [40, 60, 70]])

In [185]:
arr4 ** 2  # Power Application  (e.g 45 x 45 = 2025)

array([[2025, 1600, 1024],
       [3136, 6400, 8100],
       [1600, 3600, 4900]])

In [186]:
arr4 + 100  # Addition

array([[145, 140, 132],
       [156, 180, 190],
       [140, 160, 170]])

In [187]:
arr4 - 5   # Substruction

array([[40, 35, 27],
       [51, 75, 85],
       [35, 55, 65]])

In [188]:
arr5 = arr4 %2   # whore are divisible by 2 those are 0, rest are 1
arr5

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [189]:
arr4  # Just to show

array([[45, 40, 32],
       [56, 80, 90],
       [40, 60, 70]])

# Matrix Operation

- In Matrix operation dimenstion of both array must be same

#### Matrix Addition

In [190]:
arr4 + arr5    

array([[46, 40, 32],
       [56, 80, 90],
       [40, 60, 70]])

In [191]:
np.add(arr4, arr5)  # adding by function

array([[46, 40, 32],
       [56, 80, 90],
       [40, 60, 70]])

#### Matrix Subtraction

In [192]:
arr4 - arr5

array([[44, 40, 32],
       [56, 80, 90],
       [40, 60, 70]])

In [193]:
np.subtract(arr4, arr5)

array([[44, 40, 32],
       [56, 80, 90],
       [40, 60, 70]])

In [194]:
arr4

array([[45, 40, 32],
       [56, 80, 90],
       [40, 60, 70]])

In [195]:
arr5

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

#### Division

In [196]:
arr5 / arr4

array([[0.02222222, 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [197]:
np.divide(arr5,arr4)  # Division by function

array([[0.02222222, 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

#### Matrix Power

In [198]:
arr6 = arr4 ** arr5   # something to the power zero is "One"
arr6

array([[45,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1]], dtype=int32)

In [199]:
np.power(arr4,arr5) # Power by using function

array([[45,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1]], dtype=int32)

#### Multiplication

In [200]:
arr4 * arr5  # Multipliation in arr5 there are some 0, which make zeros the values in this multiplication

array([[45,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [201]:
np.multiply(arr4, arr5) # Normal Multiplicatoin by function

array([[45,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [202]:
arr4

array([[45, 40, 32],
       [56, 80, 90],
       [40, 60, 70]])

In [203]:
arr6

array([[45,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1]], dtype=int32)

#### Matrix Multiplication

In [204]:
arr4 @ arr6  # for matrix multiplication operator(@ sign)

array([[2097,  117,  117],
       [2690,  226,  226],
       [1930,  170,  170]])

In [205]:
np.matmul(arr4, arr6)   # Matrix Multiplication by MatMul function

array([[2097,  117,  117],
       [2690,  226,  226],
       [1930,  170,  170]])

# Load & Save NumPy Array

- np.savez: is a compressed form
- np.savetxt : text form (it will store data into text form)+
- here we will use ".npy" extension, somewhere npz (Zip format) also available

##### Allow Pickle

- it will save python object as "python object" file not as a normal or any other string,so it will store a a numpy array
- When we retriev it, we will get as numpy array
- it will store data more efficiently & effectively
- "pkl" is an extension of pickle file
- Allow pickle: true , allow to convert (read & save) file to any form easily

In [210]:
arr6

array([[45,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1]], dtype=int32)

In [208]:
np.save('arr6', arr6, allow_pickle=True)   # "arr6.npy" : is a file name, any name can be given, arr6 = file (which to be saved). There will new file in your folder when run this, but this will not open due to extension not available

#### Read file

In [212]:
np.load('arr6.npy')   # Reading file as store exactly, so like this we can read & save information & when nessary can read by loading 

array([[45,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1]])

# Statistical Operation

- NumPy allows to do operation over N Dimentional array
- Matrix mean Tabular form data

In [214]:
arr3

array([[44, 22, 45, 33],
       [34, 45, 40, 32],
       [12, 56, 80, 90],
       [50, 40, 60, 70]])

In [217]:
arr3.mean()  # mean on overal data (arr3)/ matrix

47.0625

##### Row & Column wise Mean

In [220]:
arr3.mean(axis=0)   # The parameter "axis=0" by default 0 = row wise mean. 1st row mean = 35, 2nd row mean = 40.75, 3rd row mean = 56.25 & 4th row mean = 56.25

array([35.  , 40.75, 56.25, 56.25])

In [222]:
arr3.mean(axis=1) # "axis=1" column wise mean. 1st column mean = 36, 2nd col mean = 37.75 & 59.5 for 3rd & 55 is for 4th col mean

array([36.  , 37.75, 59.5 , 55.  ])

##### Standard Deviation

- We can standard deviation when we do "square root of variance"

In [238]:
arr3

array([[44, 22, 45, 33],
       [34, 45, 40, 32],
       [12, 56, 80, 90],
       [50, 40, 60, 70]])

In [226]:
np.std(arr3)  # Standard Deviation on whole data

19.81309147382104

In [231]:
np.std(arr3, axis=0)  # Row wise std - This is for 2D

array([14.45683229, 12.2754837 , 15.5623745 , 24.78280654])

In [234]:
np.std(arr3, axis=1) # Column wise STD - this is for 2D, if it is 3 dimenstion then axis = 2, like axix=(0,1,2,3....n), like huge complexity numpy solve easily

array([ 9.35414347,  5.11737237, 30.07906249, 11.18033989])

##### Variance

In [236]:
np.var(arr3) # Variance on overall data

392.55859375

In [241]:
np.var(arr3, axis=0) # Row wise

array([209.    , 150.6875, 242.1875, 614.1875])

In [240]:
np.var(arr3,axis=1) # Column Wise

array([ 87.5   ,  26.1875, 904.75  , 125.    ])