# Numpy

- Import Numpy
- Mathmatical Operations
- Array Creation
- Adding Dimension
- np.zeros
- np.eye
- np.empty
- np.full
- np.arange   / array range
- np.linspace  (differnce between arange & linspace)
- random & randomn, randint
- Types of Array
- NDarray, item, itemsize

In [1]:
import numpy as np
np.__version__

'1.23.3'

# Math Computational

In [2]:
summ = 0
for num in range(1, 9999999):
    summ += num**2*3

summ

999999550000064999997

In [3]:
np.arange(1,9999999)

array([      1,       2,       3, ..., 9999996, 9999997, 9999998])

## Comparing Computational efficiency between general & numpy

In [4]:
# General Python, takes more time
summ1 = 0
for num in range (1,99999999):
    summ1 += num

summ1

4999999850000001

In [5]:
# Numpy sum operation     takes less time, in case of huge data we will see the different more clearly
np.sum(np.arange(1,99999999, dtype=np.int64))

4999999850000001

In [6]:
np.arange(99999999, dtype=np.int64).sum()   # alternative syntax of doing sum aggregation over numpy

4999999850000001

### Numpy is more efficinet
- Previous one needs more time than numpy
- for this operation, numpy is not taking for loop, while for same general python using loop

# Array Creation

In [7]:
# np.zeros([shape size] comma dtype with np.bit size)  # Syntax
np.zeros([3,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [8]:
np.zeros([5,5], dtype=np.int64)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [9]:
np.zeros([4, 4], dtype=np.float64)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros([2,2], dtype=np.float16)

array([[0., 0.],
       [0., 0.]], dtype=float16)

In [11]:
np.zeros([4,3], dtype=np.int64)  # rows & columns is 4:3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [12]:
np.zeros([5,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

### Adding Demension

In [13]:
np.zeros([4,3,2], dtype=np.int64)  
# 4 rows, 3 columns and 2 cell/value per row  or for each row, here is adding dimenstion as 2

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=int64)

In [14]:
np.zeros([4,3,3], dtype=np.int64)    # 3 cell/ value per row

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [15]:
np.zeros([4,3,4], dtype=np.int64)    # 4 cell/ value per row

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)

In [16]:
np.zeros([4,3,5], dtype=np.int64)    # 5 cell/ value per row

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [17]:
np.zeros([4,3], dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [18]:
np.zeros([4,5,10], dtype=np.int64)   # 10 dimension

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [19]:
np.zeros([4,8,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0

In [20]:
np.zeros([4,3,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [21]:
np.zeros([4,2,10], dtype=np.int64)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int64)

In [22]:
np.ones([4,4])    # by default dtype takes float & mentioning dtype is optional

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.ones([4,4], dtype=np.float64)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.ones([4,4], dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [25]:
np.eye(3,3)     # np.eye means "Identity Matrix", eye operation will not take square bracket [], np.eye takes only "tuple"

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(3,3, k=1)    # by default k = 0

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [27]:
np.eye(6,6)       # default k = 0

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [28]:
np.eye(6,6, k=0)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [29]:
np.eye(6,6, k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.eye(6,6, k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
np.eye(6,6, k=4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.eye(6,6, k=-4)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [33]:
np.eye(6,6, k=5)

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.eye(3,3, k=-1) 

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [35]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [36]:
np.eye(3,4,2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [37]:
np.eye(3,4,-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [38]:
np.eye(3,4,3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.eye(3,4,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.empty([3,3])

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [41]:
np.empty([3,3,3])

array([[[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 7.56908569e-321,  6.41678815e-302,  1.69348057e-301],
        [-9.28151462e+045, -2.19732017e-310,  3.06295040e+262]],

       [[ 1.69374417e+190,  2.88067937e+214,  7.21907972e+159],
        [ 4.82407136e+228,  1.99549419e+161,  6.01334434e-154],
        [ 3.68777421e+180,  3.33165731e-028, -2.23424288e-310]],

       [[ 6.93972153e+218,  4.18546840e+222,  2.43894814e-154],
        [ 1.99416198e+174,  3.64913085e+233,  5.98157061e-154],
        [ 6.01347002e-154,  2.68803869e-260,  6.01347002e-154]]])

In [42]:
np.empty([3,3,2])

array([[[1.37962049e-306, 1.24610791e-306],
        [1.11260959e-306, 1.69109959e-306],
        [9.34603679e-307, 1.42419802e-306]],

       [[1.78019082e-306, 4.45061456e-308],
        [1.24612081e-306, 1.37962049e-306],
        [9.34597567e-307, 1.29061821e-306]],

       [[1.78019625e-306, 1.11255866e-306],
        [8.90098127e-307, 9.34609790e-307],
        [3.91792279e-317, 4.39999771e+092]]])

In [43]:
np.empty([3,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [44]:
np.full([3,3], 8.5)   # it will fill the 3x3 matrix with 8.5

array([[8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5]])

In [45]:
np.full([3,3], 10.5)

array([[10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5]])

### Arange

- np.arange will not take squre backet
- mentioning dtype is optional
- it will take (start: end: step size)
- default takes int
- float & int can be mentioned in dtype
- its like a range function
- it can be reshaped

In [46]:
np.arange(1,100)   

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [47]:
np.arange(1,100, dtype=np.int64) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int64)

In [48]:
np.arange(1,100, dtype=np.float64) 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 65.,
       66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77., 78.,
       79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91.,
       92., 93., 94., 95., 96., 97., 98., 99.])

In [49]:
np.arange(1,100,5)    # step size = 5

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [50]:
np.arange(0,100,5) 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [51]:
np.linspace(1,10, 500)  # in a range 1 to 10 , it will return 500 random values

array([ 1.        ,  1.01803607,  1.03607214,  1.05410822,  1.07214429,
        1.09018036,  1.10821643,  1.12625251,  1.14428858,  1.16232465,
        1.18036072,  1.19839679,  1.21643287,  1.23446894,  1.25250501,
        1.27054108,  1.28857715,  1.30661323,  1.3246493 ,  1.34268537,
        1.36072144,  1.37875752,  1.39679359,  1.41482966,  1.43286573,
        1.4509018 ,  1.46893788,  1.48697395,  1.50501002,  1.52304609,
        1.54108216,  1.55911824,  1.57715431,  1.59519038,  1.61322645,
        1.63126253,  1.6492986 ,  1.66733467,  1.68537074,  1.70340681,
        1.72144289,  1.73947896,  1.75751503,  1.7755511 ,  1.79358717,
        1.81162325,  1.82965932,  1.84769539,  1.86573146,  1.88376754,
        1.90180361,  1.91983968,  1.93787575,  1.95591182,  1.9739479 ,
        1.99198397,  2.01002004,  2.02805611,  2.04609218,  2.06412826,
        2.08216433,  2.1002004 ,  2.11823647,  2.13627255,  2.15430862,
        2.17234469,  2.19038076,  2.20841683,  2.22645291,  2.24

##### arange return value within a range with or without step size, linspace return values in a range with asked number of values to be returned

In [52]:
np.random.randint(2,4)

2

In [53]:
np.random.randint(2,10)

9

In [54]:
np.random.randn(50)   # As I want 50 random value

array([ 1.64629067,  0.62190743,  0.77515871, -1.12882756,  0.64193135,
        1.2333627 ,  1.40261267,  1.8703207 , -2.17988586,  0.94740053,
        1.42760403,  0.56062085, -0.67947659,  2.10323467,  0.71377085,
        0.74199638,  0.89052782,  0.28944   ,  0.04896454, -0.36383334,
       -1.56520296,  2.05440768, -1.54511263,  0.10271596,  1.57614132,
       -0.04830481,  0.43900768,  0.02119347,  0.34191347,  0.43772358,
       -0.79622639,  0.46474803,  0.96189277,  0.67896348,  1.25384422,
       -1.03311058,  0.92359014,  1.08507823,  0.57817279,  1.36184797,
       -2.05984881, -1.17019744, -0.17915519,  0.59749229, -2.18986361,
        0.78856384, -0.27686829, -0.8684212 ,  0.50306682, -0.03903706])

In [55]:
np.random.randn(1,15, 5) 

array([[[ 0.75421712,  0.50805351, -0.96775698, -1.03113345,
         -0.86025044],
        [ 0.52869804, -1.72288127,  0.42844988,  1.16883568,
         -1.02880807],
        [ 0.91343141,  0.11544887,  0.20701337, -1.27117128,
          0.02544216],
        [-0.40558732, -1.59760103,  0.79293053, -0.7248354 ,
         -0.09966262],
        [-0.71677884, -1.00965729,  2.80393756,  1.31469585,
          1.21950994],
        [ 0.38912576, -0.05225783,  0.81955549, -0.07656195,
         -0.39126883],
        [ 0.51505176,  0.75931178,  1.33150798,  1.99961075,
          1.22879012],
        [-0.65906059, -0.22048639,  0.09336792, -0.35545081,
          0.40416069],
        [ 0.4369857 ,  1.57134598,  1.00492904,  1.78389731,
          0.57749719],
        [-0.08780006, -0.11299285,  0.12330135,  0.22640581,
         -0.83263845],
        [ 2.59846206,  0.37476481, -0.58278924,  0.28399214,
          1.85130927],
        [ 0.94686305,  1.75413719, -0.8787951 ,  0.35647174,
          1.163

# Types of Array

- Convert any kind of iterable object into list, array mean numpy array
- by default it takes int types
- dtype can be mentioned as per need

In [56]:
interger = np.array([2,3,5,6,23,56,58])  # default integer
interger

array([ 2,  3,  5,  6, 23, 56, 58])

In [57]:
defined_integer = np.array([2,3,4,5,5,50,75,80,80], dtype=np.int64)   # mention dtype as int64
defined_integer

array([ 2,  3,  4,  5,  5, 50, 75, 80, 80], dtype=int64)

In [58]:
float = np.array([2,3,4,5,5,50,75,80,80], dtype=np.float64)  # mention dtype as float64
float

array([ 2.,  3.,  4.,  5.,  5., 50., 75., 80., 80.])

In [59]:
bool = np.array([True, False, True, True, False], dtype=np.bool8)  # dtype as boolean
bool

array([ True, False,  True,  True, False])

In [60]:
empty = np.empty([3,3], dtype=np.complex64)
empty

array([[0.+2.j       , 0.+2.125j    , 0.+2.25j     ],
       [0.+2.3125j   , 0.+2.3125j   , 0.+3.140625j ],
       [0.+3.2929688j, 0.+3.3125j   , 0.+3.3125j   ]], dtype=complex64)

In [61]:
string = np.array(['apple','orange', 'banana', 'grapes'], dtype=np.string_)  # string type, mentioning dtype is recommended
string

array([b'apple', b'orange', b'banana', b'grapes'], dtype='|S6')

# NDarray Object Inspection

- ndim : there is function that is 'ndim' by which we can extract/ find dimention
- shape : by which we can know the shape (number of rows & columns)
- In NDarray object Inspection, type(ndim), shape is very important

In [62]:
string.ndim

1

In [63]:
empty

array([[0.+2.j       , 0.+2.125j    , 0.+2.25j     ],
       [0.+2.3125j   , 0.+2.3125j   , 0.+3.140625j ],
       [0.+3.2929688j, 0.+3.3125j   , 0.+3.3125j   ]], dtype=complex64)

In [64]:
empty.ndim  # lets verify the the empty output, there a two bracket inside array or array inside array, value as per rows & columns

2

In [65]:
empty.shape  # In order to verify the number of rows & columns

(3, 3)

In [66]:
interger

array([ 2,  3,  5,  6, 23, 56, 58])

In [67]:
interger.shape  # 7 value with 1 dimension

(7,)

In [69]:
empty.itemsize # Represent the byte size of each item
string.itemsize

6

In [70]:
string.item(0) # checking index value, we can fetch data more easily

b'apple'

In [72]:
bool

array([ True, False,  True,  True, False])

In [73]:
bool.any()  # Check & verify wheter any true in bool variable, its returning true becasue of lots of true available in bool

True

In [74]:
bool.all() # Check whether all true or not. .any & .all function basically applied on boolean value

False

In [75]:
string.T # Transpose its not properloy understandable because of 1D, it will more clear when apply on 2D

array([b'apple', b'orange', b'banana', b'grapes'], dtype='|S6')

In [76]:
# Checking Data type
empty.dtype

dtype('complex64')

In [77]:
interger.dtype

dtype('int32')

In [78]:
interger.itemsize

4

In [80]:
# We can directly inspect data type from here & depending on that we can decide what kind of steps to be applied for this.becasue we cant run numerical operation on str, so this will help to first understand
string.dtype  

dtype('S6')

In [81]:
empty.size # to know the total number of elements. empty is 3x3 matrix so total 9 elements

9