# Linear Alzebra

- Linear Alzebra
- Dot Product
- Determinant
- Inverse
- Eigenvalues and eigenvectors

In [20]:
import numpy as np
np.__version__

'1.23.3'

# Linear Alzebra

In [21]:
arr1 = np.array(
    [
        [10, 15, 20],   # 1st Index
        [70, 76, 89],   # 2nd Index
        [52, 45, 78]    # 3rd Index
    ]
)

# Import Linear Alzebra from Numpy

- Here linage/ linear alzebra is a sub module imported from numpy


In [22]:
from numpy import linalg as lg   

In [23]:
arr1

array([[10, 15, 20],
       [70, 76, 89],
       [52, 45, 78]])

- In mathematics, the determinant is a scalar value that is a function of the entries of a square matrix. It characterizes some properties of the matrix and the linear map represented by the matrix.

In [24]:
lg.det(arr1)   # Determinant of arr

-9290.000000000015

In [25]:
lg.inv(arr1)  # inverse

array([[-0.20699677,  0.02906351,  0.01991389],
       [ 0.08955867,  0.02798708, -0.05489774],
       [ 0.08632939, -0.03552207,  0.03121636]])

In [26]:
arr1.transpose()  # Transpose, e.g it will convert row to column & column to row

array([[10, 70, 52],
       [15, 76, 45],
       [20, 89, 78]])

In [27]:
arr1.T  # alternative of transpose

array([[10, 70, 52],
       [15, 76, 45],
       [20, 89, 78]])

# Dot Product Operation

- Need two matrix to operate dot product

In [28]:
arr1

array([[10, 15, 20],
       [70, 76, 89],
       [52, 45, 78]])

In [29]:
arr2 = np.array(
    [
        [20, 30, 40],
        [15, 20, 25],
        [30, 35, 40]
    ]
)

### 3 x 3 matrix dot product

#### Basic Idea

- 1st row (matrix 1) x 1st columns (matrix 2)
- 1st row (matrix 1) x 2nd columns (matrix 2)
- 1st row (matrix 1) x 3rd columns (matrix 2)

In [30]:
np.dot(arr1,arr2)  # Dot Product

array([[1025, 1300, 1575],
       [5210, 6735, 8260],
       [4055, 5190, 6325]])

#### Dot Product Verification

In [31]:
(10*20) + (15*15) + (20*30)    # 1st row of array1 * 1st columns of array 2  = 1025 verified

1025

In [32]:
(10*30) + (15*20) + (20*35)    # 1st row of array1 * 2 nd columns of array 2  = 1300 verified

1300

In [33]:
(10*40) + (15*25) + (20*40)    # 1st row of array1 * 3 rd columns of array 2  = 1575 verified

1575

# Dot Product of Two Vector

- Given Two Vectory, vector A & vector B, Find dot product of vector A & vector B

In [34]:
a = [4, 1, 2, 3]  # Vector A

In [35]:
b = [3, 1, 7, 2] # Vector B

In [36]:
np.dot(a,b)

33

#### Dot Product Calucation of Two Vector (A & B) shown as details/ working

In [37]:
(4 * 3) + (1 * 1) + (2 * 7) + (3 * 2)   # Dot Product Calculation of two vector is verifed

33

# Eigenvalues and eigenvectors

- The eigenvector is a vector that is associated with a set of linear equations. The eigenvector of a matrix is also known as a latent vector, proper vector, or characteristic vector
- In linear algebra, an eigenvector or characteristic vector of a linear transformation is a nonzero vector that changes at most by a scalar factor when that linear transformation is applied to it.
- The corresponding eigenvalue, often denoted by \lambda, is the factor by which the eigenvector is scaled.

In [38]:
lg.eig(arr1)  # Eigenvector of normal vertor .eg arr1

(array([154.73900897,  -4.39602447,  13.6570155 ]),
 array([[ 0.16279192,  0.86253644, -0.04101419],
        [ 0.79901468, -0.37530894, -0.80291219],
        [ 0.57885606, -0.33937308,  0.59468467]]))